declare module 'vue' {
  export interface GlobalComponents {
    FaAvatar: typeof import('./index')['FaAvatar']
    FaButton: typeof import('./index')['FaButton']
    FaButtonGroup: typeof import('./index')['FaButtonGroup']
    FaCard: typeof import('./index')['FaCard']
    FaCheckbox: typeof import('./index')['FaCheckbox']
    FaCollapsible: typeof import('./index')['FaCollapsible']
    FaContextMenu: typeof import('./index')['FaContextMenu']
    FaDivider: typeof import('./index')['FaDivider']
    FaDrawer: typeof import('./index')['FaDrawer']
    FaDropdown: typeof import('./index')['FaDropdown']
    FaFileUpload: typeof import('./index')['FaFileUpload']
    FaFixedBar: typeof import('./index')['FaFixedBar']
    FaHoverCard: typeof import('./index')['FaHoverCard']
    FaIcon: typeof import('./index')['FaIcon']
    FaImagePreview: typeof import('./index')['FaImagePreview']
    FaImageUpload: typeof import('./index')['FaImageUpload']
    FaInput: typeof import('./index')['FaInput']
    FaInputOTP: typeof import('./index')['FaInputOTP']
    FaKbd: typeof import('./index')['FaKbd']
    FaKbdGroup: typeof import('./index')['FaKbdGroup']
    FaLabel: typeof import('./index')['FaLabel']
    FaModal: typeof import('./index')['FaModal']
    FaNumberField: typeof import('./index')['FaNumberField']
    FaPageHeader: typeof import('./index')['FaPageHeader']
    FaPageMain: typeof import('./index')['FaPageMain']
    FaPasswordStrength: typeof import('./index')['FaPasswordStrength']
    FaPopover: typeof import('./index')['FaPopover']
    FaProgress: typeof import('./index')['FaProgress']
    FaRadioGroup: typeof import('./index')['FaRadioGroup']
    FaScrollArea: typeof import('./index')['FaScrollArea']
    FaSearchBar: typeof import('./index')['FaSearchBar']
    FaSelect: typeof import('./index')['FaSelect']
    FaSlider: typeof import('./index')['FaSlider']
    FaSwitch: typeof import('./index')['FaSwitch']
    FaTabs: typeof import('./index')['FaTabs']
    FaTextarea: typeof import('./index')['FaTextarea']
    FaToast: typeof import('./index')['FaToast']
    FaTooltip: typeof import('./index')['FaTooltip']
    FaTrend: typeof import('./index')['FaTrend']
  }
}

export {}
